package io.testforge.api.fuzz;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;

/**
 * Writer for TestForge's generated {@code schemathesis.toml} configuration file.
 *
 * <p>TestForge promises that mutating HTTP methods will never be sent unless two keys
 * are present: the method is listed in {@code forge.api-fuzz.methods} AND
 * {@code allow-unsafe-methods=true}. To enforce this against Schemathesis (which by default
 * generates unexpected HTTP methods in its coverage phase, e.g. TRACE), TestForge writes
 * a generated configuration file containing:
 * <pre>
 * [phases.coverage]
 * unexpected-methods = []
 * </pre>
 * when {@link FuzzSafetyPolicy#suppressesUnexpectedMethods()} returns {@code true}.
 *
 * <p><strong>Secrets and User Configuration Handling:</strong>
 * If the user supplies an external configuration file via {@code forge.api-fuzz.config-file},
 * TestForge MUST NOT parse, merge, or copy its contents into TestForge artifacts.
 * User configuration files may contain sensitive credentials (e.g. authentication tokens). Instead,
 * the user config is passed to Schemathesis separately via CLI configuration flags as an overlay.
 * TestForge's generated file is kept strictly free of secrets.
 */
public class SchemathesisConfigFile {

    public static final String CONFIG_FILENAME = "schemathesis.toml";

    /**
     * Writes the generated {@code schemathesis.toml} configuration file into the specified directory.
     *
     * @param outputDir the directory where {@code schemathesis.toml} should be created
     * @param policy    the safety policy driving the configuration content
     * @return the path to the written {@code schemathesis.toml} file
     * @throws ApiFuzzException if writing the configuration file fails
     */
    public Path write(Path outputDir, FuzzSafetyPolicy policy) {
        Objects.requireNonNull(outputDir, "outputDir cannot be null");
        Objects.requireNonNull(policy, "policy cannot be null");

        try {
            Files.createDirectories(outputDir);
            Path configFile = outputDir.resolve(CONFIG_FILENAME);

            StringBuilder content = new StringBuilder();
            content.append("# Generated by TestForge - DO NOT EDIT MANUALLY\n");

            if (policy.suppressesUnexpectedMethods()) {
                content.append("[phases.coverage]\n");
                content.append("unexpected-methods = []\n");
            } else {
                content.append("# unexpected-methods left at Schemathesis default because allowUnsafeMethods=true\n");
            }

            Files.writeString(configFile, content.toString());
            return configFile;
        } catch (IOException e) {
            throw new ApiFuzzException("Failed to write Schemathesis configuration file in " + outputDir, e);
        }
    }

    /**
     * Writes the generated {@code schemathesis.toml} configuration file into the specified directory.
     *
     * @param outputDir the directory where {@code schemathesis.toml} should be created
     * @param policy    the safety policy driving the configuration content
     * @return the path to the written {@code schemathesis.toml} file
     */
    public static Path generate(Path outputDir, FuzzSafetyPolicy policy) {
        return new SchemathesisConfigFile().write(outputDir, policy);
    }
}
